environment:
  matrix:
    - PYTHON: "C:\\Python37"
      TOXENV: "py37"
    - PYTHON: "C:\\Python36"
      TOXENV: "py36"
    - PYTHON: "C:\\Python35"
      TOXENV: "py35"
    - PYTHON: "C:\\Python34"
      TOXENV: "py34"
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"

cache:
    - '%LOCALAPPDATA%\pip\Cache'

version: '{branch}.{build}'

install:
  - "%PYTHON%\\python.exe -m pip install -U tox virtualenv"

build: off

test_script:
  - "%PYTHON%\\Scripts\\tox.exe"
